import { videoCardType } from '@/types'

export const videos: videoCardType[] = [
    {
        id: 1,
        title: 'Gary Vee Explains How He Made $90 Million on NFTs & Why They’ll Change the World',
        channel: '@BlueWard2',
        price: 140,
        avatar: '/usersImg/user1.png',
        poster: '/fakeImg/video-14.jpg',
    },
    {
        id: 2,
        title: "No One Is Paying Attention To What's Really Going On With NFTs",
        channel: 'GarrisonF',
        price: 20,
        avatar: '/usersImg/user2.png',
        poster: '/fakeImg/video-13.jpg',
    },
    {
        id: 3,
        title: 'Bored Ape Yacht Club Creators Explain How Steph Curry & Bieber Got Their NFT & How BAYC is Worth $4B',
        channel: 'Johnny Vnice',
        price: 45,
        avatar: '/usersImg/user3.png',
        poster: '/fakeImg/video-12.jpg',
    },
    {
        id: 4,
        title: 'The Exploding Card Market',
        channel: 'Thunder Mary',
        price: 56,
        avatar: '/usersImg/user4.png',
        poster: '/fakeImg/video-2.jpg',
    },
    {
        id: 5,
        title: 'Web3/Metaverse Chat With Mark Zuckerberg',
        channel: 'Gary Vee',
        price: 122,
        avatar: '/usersImg/user5.png',
        poster: '/fakeImg/video-3.jpg',
    },
    {
        id: 6,
        title: 'If You Understand This Video About NFTs You Are in the Top 10% of People That Get It',
        channel: 'Impudent Jok',
        price: 12,
        avatar: '/usersImg/user6.png',
        poster: '/fakeImg/video-4.jpg',
    },
    {
        id: 7,
        title: 'What You Need To Know About The NFT World',
        channel: 'Yellow Stone',
        price: 43,
        avatar: '/usersImg/user7.png',
        poster: '/fakeImg/video-5.jpg',
    },
    {
        id: 8,
        title: 'Wolf of Wall Street Calls Out Crypto Scammers & Shares Leonardo DiCaprio Stories',
        channel: 'Mr Hawk',
        price: 78,
        avatar: '/usersImg/user8.png',
        poster: '/fakeImg/video-6.jpg',
    },
    {
        id: 9,
        title: 'How NFTs are shaking up the art world | DW Documentary',
        channel: 'Manga',
        price: 212,
        avatar: '/usersImg/user9.png',
        poster: '/fakeImg/video-7.jpg',
    },
    {
        id: 10,
        title: 'Why are people collecting NFTs? - 6 Minute English',
        channel: 'BBC English',
        price: 120,
        avatar: '/usersImg/user10.png',
        poster: '/fakeImg/video-8.jpg',
    },
    {
        id: 11,
        title: 'The Ultimate NFT Course: Beginner to Advanced Buy Sell',
        channel: 'Hustlers Point',
        price: 13,
        avatar: '/usersImg/user11.png',
        poster: '/fakeImg/video-9.jpg',
    },
    {
        id: 12,
        title: 'NFTs - SNL',
        channel: 'SNL',
        price: 278,
        avatar: '/usersImg/user12.png',
        poster: '/fakeImg/video-10.jpg',
    },
]
